// packages/app/src/tui/components/StatusBar.vue
<script setup lang="ts">
import { Box, Text } from '@andrew_l/vue-stdout';
import { useTuiStore } from '../composables/useTuiStore.ts';

const { system } = useTuiStore();
</script>

<template>
  <Box
    flexDirection="row"
    justifyContent="space-between"
    :paddingX="1"
    :flexShrink="0"
    :height="1"
  >
    <Box :flexShrink="1" overflow="hidden">
      <Text wrap="truncate-end">
        <template v-if="system">
          <Text color="gray">[system] </Text>
          <Text :color="system.level === 'error' ? 'red' : 'white'">{{
            system.text
          }}</Text>
        </template>
        <Text v-else color="gray">[system] ready</Text>
      </Text>
    </Box>
    <Box :flexShrink="0">
      <Text color="gray">↑/↓ · →/← · PgUp/PgDn · s · ⇧S · r · f · q</Text>
    </Box>
  </Box>
</template>

// packages/app/src/tui/components/StatusBar.tsx
import { Box, Text } from 'ink';
import type { JSX } from 'react';
import { useStoreSnapshot, useTuiStore } from './useTuiStore.ts';

export function StatusBar(): JSX.Element {
  useStoreSnapshot();
  const store = useTuiStore();
  const sys = store.system;

  return (
    <Box
      flexDirection="row"
      justifyContent="space-between"
      paddingX={1}
      flexShrink={0}
      height={1}
    >
      <Box flexShrink={1} overflow="hidden">
        <Text wrap="truncate-end">
          {sys ? (
            <>
              <Text color="gray">[system] </Text>
              <Text color={sys.level === 'error' ? 'red' : 'white'}>
                {sys.text}
              </Text>
            </>
          ) : (
            <Text color="gray">[system] ready</Text>
          )}
        </Text>
      </Box>
      <Box flexShrink={0}>
        <Text color="gray">
          ↑/↓ · →/← · PgUp/PgDn · s · ⇧S · r · f · q
        </Text>
      </Box>
    </Box>
  );
}
